[package]
name = "szumi"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
image = "0.24"
color-eyre = "0.6.2"
winit = "0.28.0"

[profile.dev]
opt-level = 1 